In [2]:
#importing one_hot from tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
voc_size=10000#size of the vocabulary

In [7]:
#one hot representaion
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[2554, 5110, 2941, 7447], [2554, 5110, 2941, 6875], [2554, 2432, 2941, 3369], [5502, 2305, 8357, 2642, 3884], [5502, 2305, 8357, 2642, 5940], [4464, 2554, 2481, 2941, 9495], [4569, 9041, 5461, 2642]]


**word embedding representation**

In [14]:
#importing the neccessary libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd


In [13]:
sent_length=8 #sentence length after padding
embedded_docs=pad_sequences(onehot_repr,padding="pre",maxlen=sent_length) #padding=pre means zero will be infront
print(embedded_docs)# sentences after padding
#padding is done to make the sentences length equal to one another

[[   0    0    0    0 2554 5110 2941 7447]
 [   0    0    0    0 2554 5110 2941 6875]
 [   0    0    0    0 2554 2432 2941 3369]
 [   0    0    0 5502 2305 8357 2642 3884]
 [   0    0    0 5502 2305 8357 2642 5940]
 [   0    0    0 4464 2554 2481 2941 9495]
 [   0    0    0    0 4569 9041 5461 2642]]


In [15]:
table1=pd.DataFrame(embedded_docs)
table1

0  1  2     3     4     5     6     7
0  0  0  0     0  2554  5110  2941  7447
1  0  0  0     0  2554  5110  2941  6875
2  0  0  0     0  2554  2432  2941  3369
3  0  0  0  5502  2305  8357  2642  3884
4  0  0  0  5502  2305  8357  2642  5940
5  0  0  0  4464  2554  2481  2941  9495
6  0  0  0     0  4569  9041  5461  2642

In [16]:
dim=15#dimensions of the each vector that will represent the word

In [17]:
#creating the embedding model
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam","mse")

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 15)             150000    
                                                                 
Total params: 150000 (585.94 KB)
Trainable params: 150000 (585.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
#word embedding table
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 111ms/step
[[[-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581
   -0.00918948 -0.01294275 -0.01965785  0.00796426 -0.02898743
   -0.04492179 -0.01523607  0.02294992  0.04837834  0.04899461]
  [-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581
   -0.00918948 -0.01294275 -0.01965785  0.00796426 -0.02898743
   -0.04492179 -0.01523607  0.02294992  0.04837834  0.04899461]
  [-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581
   -0.00918948 -0.01294275 -0.01965785  0.00796426 -0.02898743
   -0.04492179 -0.01523607  0.02294992  0.04837834  0.04899461]
  [-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581
   -0.00918948 -0.01294275 -0.01965785  0.00796426 -0.02898743
   -0.04492179 -0.01523607  0.02294992  0.04837834  0.04899461]
  [ 0.00731599  0.02174313 -0.03909808 -0.02871685 -0.01450491
   -0.02639047 -0.01805775 -0.02063354 -0.01265844  0.03945389
    0.0158883   0.00587523 -0.02752456  0.00881505  0.0344283

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 2554, 5110, 2941, 7447], dtype=int32)

In [22]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 20ms/step
[[-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581 -0.00918948
  -0.01294275 -0.01965785  0.00796426 -0.02898743 -0.04492179 -0.01523607
   0.02294992  0.04837834  0.04899461]
 [-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581 -0.00918948
  -0.01294275 -0.01965785  0.00796426 -0.02898743 -0.04492179 -0.01523607
   0.02294992  0.04837834  0.04899461]
 [-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581 -0.00918948
  -0.01294275 -0.01965785  0.00796426 -0.02898743 -0.04492179 -0.01523607
   0.02294992  0.04837834  0.04899461]
 [-0.01629945  0.02930249  0.00402212 -0.03211266 -0.01900581 -0.00918948
  -0.01294275 -0.01965785  0.00796426 -0.02898743 -0.04492179 -0.01523607
   0.02294992  0.04837834  0.04899461]
 [ 0.00731599  0.02174313 -0.03909808 -0.02871685 -0.01450491 -0.02639047
  -0.01805775 -0.02063354 -0.01265844  0.03945389  0.0158883   0.00587523
  -0.02752456  0.00881505  0.03442837]
 [-0.02810088